### PR TITLE
Fix for #13

### LINKED ISSUE #13: When using from IPython, total time reported at the end accumulates.
If I profile a script such as this one:

    def main():
        # do something
    
    if __name__ == '__main__':
        import statprof
        statprof.start()
        try:
            main()
        finally:
            statprof.stop()
            statprof.display()

and call it from IPython by repeatedly executing `run script.py`, the total time grows each time by duration of the execution (e.g. 1s, 2s, 3s, ...).

Without looking very deeply into the code, the function `clock()` gets its time from `os.times()`. I am not certain what the values in the list returned by it represent, but the result of `clock()` seems to be the same as what `time.clock()`, which is the CPU time since the module has been imported and that matches well with the observed behavior. Maybe it would be better to use `time.time()` (which returns an absolute time value), then save the current time at `statprof.start()`, and calc the difference by `time.time() - starttime`?

Also, I've noticed this today, but I've been doing the same thing a couple of days ago and was getting more or less constant values for each run. But I can't remember whether I've been working from inside IPython or calling the script directly from the shell. So I'm not sure it really is well reproducible.

### PR DESCRIPTION
**Pull request by elpres**
This should fix #13. Accumulated time counter wasn't reset between sessions.

### CODE REVIEW

**Comment by durin42** [comment]
Any chance I could get a test to go with the fix?

**Comment by elpres** [comment]
Oh, I'm not sure how to do that. Is there a way to read out the accumulated time from outside? The instance of `ProfileState` that contains the counter is never returned to the caller.

But I've just noticed another thing: This behavior I've reported in #13 is probably by design. There is a method `reset` that wipes all internal state, which is probably how the module is supposed to be used in an IPython session:

```python
statprof.reset()
with statprof.profile():
    some_work()
```

So, rather than "fixing" this, it might be helpful to mention this situation somewhere in the docs.

**Comment by durin42** [comment]
Ah, fair point - I forgot about the reset thing. Looks like we should document that. Want to draft a doc fix patch instead of this one?

**Comment by elpres** [comment]
Yeah, I'll look into that.

**Pull request closed without merging**
